/**
 * ImageGeneratepage Component
 * 
 * 텍스트 프롬프트를 기반으로 이미지를 생성하고 변환하는 메인 컴포넌트입니다.
 * 주요 기능:
 * - 텍스트 프롬프트 기반 초기 이미지 생성
 * - 생성된 이미지의 스타일 변환
 * - 이미지 확대/축소 기능
 * - 히스토리 관리 (저장, 불러오기, 내보내기)
 */

// src/components/ImageGeneratepage.jsx
import React, { useState, useRef, useEffect, useCallback, useMemo } from "react";
import styled, { createGlobalStyle, keyframes, ThemeProvider } from "styled-components";
import { generateInitialImage, generateFinalImage } from "../api";

// 개발 및 테스트를 위한 상수 정의
const USE_DUMMY_DATA = true; // true: 더미 데이터 사용, false: 실제 API 호출

// 더미 이미지 데이터 - 개발 및 테스트용
const DUMMY_IMAGES = {
  "Stable Diffusion 1.5": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#FF6B6B"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 1.5</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#FF8787"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 1.5</text>
      </svg>
    `)}`
  },
  "Stable Diffusion 3.5": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4D96FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 3.5</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#6BA6FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 3.5</text>
      </svg>
    `)}`
  },
  "Disco GAN": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4D96FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Disco GAN</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#9C27B0"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Disco GAN</text>
      </svg>
    `)}`
  },
  "Style GAN-ada": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4D96FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Style GAN-ada</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4CAF50"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Style GAN-ada</text>
      </svg>
    `)}`
  }
};

// 사용 가능한 모델 옵션 정의
const INITIAL_MODEL_OPTIONS = [
  { id: "Stable Diffusion 1.5", name: "Stable Diffusion 1.5", label: "Stable Diffusion 1.5" },
  { id: "Stable Diffusion 3.5", name: "Stable Diffusion 3.5", label: "Stable Diffusion 3.5" }
];

const FINAL_MODEL_OPTIONS = [
  { id: "Disco GAN", name: "Disco GAN", label: "Disco GAN" },
  { id: "Style GAN-ada", name: "Style GAN-ada", label: "Style GAN-ada" }
];

// 모델 설명 정의
const MODEL_DESCRIPTIONS = {
  "Stable Diffusion 1.5": {
    description: "안정적인 이미지 생성이 가능한 기본 모델",
    pros: ["높은 안정성", "빠른 생성 속도", "일관된 품질"],
    cons: ["창의성 제한적", "복잡한 디테일 표현 어려움"]
  },
  "Stable Diffusion 3.5": {
    description: "더 높은 품질과 창의적인 이미지 생성이 가능한 최신 모델",
    pros: ["높은 품질", "창의적인 표현", "세밀한 디테일"],
    cons: ["느린 생성 속도", "더 많은 리소스 사용"]
  },
  "Disco GAN": {
    description: "스타일 변환에 특화된 모델",
    pros: ["강력한 스타일 변환", "다양한 스타일 적용", "빠른 처리 속도"],
    cons: ["원본 구조 보존 어려움", "불안정한 결과"]
  },
  "Style GAN-ada": {
    description: "고품질 스타일 변환과 세밀한 조정이 가능한 모델",
    pros: ["높은 품질", "세밀한 파라미터 조정", "안정적인 결과"],
    cons: ["복잡한 설정", "느린 처리 속도"]
  }
};

// 테마 정의
const lightTheme = {
  primary: '#007bff',
  success: '#28a745',
  danger: '#dc3545',
  background: '#f5f5f5',
  surface: '#ffffff',
  text: '#000000',
  textSecondary: '#666666',
  border: '#dddddd',
  shadow: 'rgba(0, 0, 0, 0.1)',
  overlay: 'rgba(0, 0, 0, 0.5)',
  spinnerBorder: '#f3f3f3',
  spinnerActive: '#3498db'
};

const darkTheme = {
  primary: '#0d6efd',
  success: '#198754',
  danger: '#dc3545',
  background: '#121212',
  surface: '#1e1e1e',
  text: '#ffffff',
  textSecondary: '#a0a0a0',
  border: '#333333',
  shadow: 'rgba(0, 0, 0, 0.3)',
  overlay: 'rgba(0, 0, 0, 0.7)',
  spinnerBorder: '#333333',
  spinnerActive: '#0d6efd'
};

/**
 * 로딩 스피너 컴포넌트
 * 이미지 생성/변환 중 로딩 상태를 표시
 */
const LoadingSpinner = styled.div`
  width: 50px;
  height: 50px;
  border: 5px solid ${props => props.theme.spinnerBorder};
  border-top: 5px solid ${props => props.theme.spinnerActive};
  border-radius: 50%;
  animation: spin 1s linear infinite;
`;

/**
 * 이미지 확대 컴포넌트
 * 마우스 오버 시 이미지의 특정 부분을 확대하여 보여줌
 */
const ImageMagnifier = ({ imageUrl, alt }) => {
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [showMagnifier, setShowMagnifier] = useState(false);
  const imgRef = useRef(null);

  const magnifierWidth = 200;
  const magnifierHeight = 200;
  const zoomLevel = 2.5;

  const handleMouseMove = (e) => {
    const elem = imgRef.current;
    if (!elem) return;

    const { top, left, width, height } = elem.getBoundingClientRect();
    const x = e.clientX - left;
    const y = e.clientY - top;

    setPosition({
      x: Math.max(0, Math.min(x, width)),
      y: Math.max(0, Math.min(y, height))
    });
  };

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "400px",
        display: "flex",
        justifyContent: "center",
        alignItems: "center"
      }}
    >
      <img
        ref={imgRef}
        src={imageUrl}
        alt={alt}
        style={{
          maxWidth: "100%",
          height: "400px",
          objectFit: "contain",
          borderRadius: "4px"
        }}
        onMouseEnter={() => setShowMagnifier(true)}
        onMouseLeave={() => setShowMagnifier(false)}
        onMouseMove={handleMouseMove}
      />
      {showMagnifier && (
        <div
          style={{
            position: "absolute",
            left: `${position.x - magnifierWidth / 2}px`,
            top: `${position.y - magnifierHeight / 2}px`,
            width: `${magnifierWidth}px`,
            height: `${magnifierHeight}px`,
            border: "2px solid #007bff",
            borderRadius: "4px",
            pointerEvents: "none",
            overflow: "hidden",
            backgroundColor: "white",
            zIndex: 100,
            boxShadow: "0 2px 8px rgba(0, 0, 0, 0.2)"
          }}
        >
          <img
            src={imageUrl}
            alt={alt}
            style={{
              position: "absolute",
              left: `${-position.x * (zoomLevel - 1) - (magnifierWidth / 2)}px`,
              top: `${-position.y * (zoomLevel - 1) - (magnifierHeight / 2)}px`,
              maxWidth: "none",
              height: `${400 * zoomLevel}px`,
              objectFit: "contain"
            }}
          />
        </div>
      )}
    </div>
  );
};

/**
 * 전역 스타일 정의
 * 애니메이션 키프레임과 전역적으로 적용될 스타일 설정
 */
const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    background-color: ${props => props.theme.background};
    color: ${props => props.theme.text};
    transition: all 0.3s ease;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  @keyframes slideIn {
    from { transform: translateX(100%); }
    to { transform: translateX(0); }
  }
  @keyframes slideOut {
    from { transform: translateX(0); }
    to { transform: translateX(100%); }
  }
`;

const Container = styled.div`
  width: 100vw;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: ${props => props.theme.background};
  margin: 0;
  padding: 0;
  position: relative;
  overflow: hidden;
  color: ${props => props.theme.text};
`;

const MainContent = styled.div`
  width: 100%;
  max-width: 800px;
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding: 20px;
  margin: 0 auto;
`;

const PromptDisplay = styled.div`
  width: 100%;
  background-color: ${props => props.theme.surface};
  padding: 20px;
  border-radius: 12px;
  box-shadow: 0 2px 4px ${props => props.theme.shadow};
  margin: 0 auto;
`;

const ContentArea = styled.div`
  display: flex;
  flex-direction: column;
  gap: 20px;
  width: 100%;
`;

const ImageControlArea = styled.div`
  width: 100%;
  background-color: ${props => props.theme.surface};
  padding: 20px;
  border-radius: 12px;
  box-shadow: 0 2px 4px ${props => props.theme.shadow};
`;

const Form = styled.form.attrs(props => ({
  'aria-label': 'Image generation form',
}))`
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
`;

const Input = styled.input.attrs(props => ({
  'aria-label': 'Text prompt input',
  'aria-disabled': props.disabled,
  'aria-required': props.required,
}))`
  flex: 1;
  padding: 12px;
  border-radius: 6px;
  border: 1px solid ${props => props.theme.border};
  font-size: 1rem;
  background-color: ${props => props.theme.surface};
  color: ${props => props.theme.text};

  &::placeholder {
    color: ${props => props.theme.textSecondary};
  }
`;

const Button = styled.button.attrs(props => ({
  'aria-disabled': props.disabled,
  role: 'button',
}))`
  padding: 12px 24px;
  background-color: ${props => {
    if (props.variant === 'success') return props.theme.success;
    if (props.variant === 'danger') return props.theme.danger;
    return props.theme.primary;
  }};
  color: white;
  border: none;
  border-radius: 6px;
  cursor: ${props => props.disabled ? 'not-allowed' : 'pointer'};
  opacity: ${props => props.disabled ? 0.6 : 1};
  font-size: 1rem;
  white-space: nowrap;
  transition: all 0.2s ease;

  &:hover:not(:disabled) {
    filter: brightness(1.1);
  }
`;

const ImageContainer = styled.div`
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 20px;
  margin-bottom: 20px;
  position: relative;
  min-height: 200px;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const StyledImage = styled.img`
  max-width: 100%;
  height: auto;
  border-radius: 4px;
  object-fit: contain;
  aspect-ratio: 1;
`;

const LoadingOverlay = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: ${props => props.theme.background};
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 10;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 2px 8px ${props => props.theme.shadow};
`;

const ButtonGroup = styled.div`
  display: flex;
  gap: 10px;
  justify-content: center;
  margin-top: 20px;
`;

const ModelCard = styled.div`
  display: flex;
  flex-direction: column;
  padding: 16px;
  border-radius: 12px;
  background-color: ${props => props.isSelected ? props.theme.primary + '20' : props.theme.surface};
  border: 2px solid ${props => props.isSelected ? props.theme.primary : 'transparent'};
  cursor: pointer;
  transition: all 0.3s ease;
  position: relative;
  overflow: hidden;

  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px ${props => props.theme.shadow};
  }

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 4px;
    height: 100%;
    background-color: ${props => props.isSelected ? props.theme.primary : 'transparent'};
    transition: all 0.3s ease;
  }
`;

const ModelHeader = styled.div`
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
`;

const ModelIcon = ({ option }) => {
  if (option.id === "Stable Diffusion 1.5") return "🎨";
  if (option.id === "Stable Diffusion 3.5") return "🖼️";
  if (option.id === "Disco GAN") return "💃";
  if (option.id === "Style GAN-ada") return "✨";
  return "🎨";
};

const ModelTitle = styled.div`
  font-weight: 600;
  font-size: 1.1rem;
  color: ${props => props.theme.text};
`;

const ModelDescription = styled.div`
  margin-bottom: 8px;
  color: ${props => props.theme.textSecondary};
`;

const ModelFeatures = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
`;

const FeatureItem = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 0.85rem;
  color: ${props => props.isPro ? props.theme.success : props.theme.danger};
`;

const FeatureIcon = styled.span`
  font-size: 1rem;
`;

const ModelSelect = styled.div`
  background-color: ${props => props.theme.surface};
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 20px;
  box-shadow: 0 2px 8px ${props => props.theme.shadow};
`;

const ModelOptions = styled.div`
  display: flex;
  flex-direction: column;
  gap: 16px;
`;

const ModelSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 12px;
`;

const SectionTitle = styled.div`
  font-weight: 600;
  color: ${props => props.theme.textSecondary};
  margin-bottom: 8px;
`;

const ErrorMessage = styled.div`
  padding: 20px;
  background-color: ${props => props.theme.danger}15;
  border-radius: 6px;
  color: ${props => props.theme.danger};
  border: 1px solid ${props => props.theme.danger}30;
`;

const HistoryButton = styled.div`
  position: fixed;
  right: ${props => props.showSidebar ? "320px" : "20px"};
  top: 20px;
  z-index: 1000;
  transition: right 0.3s ease-in-out;
`;

const SidebarTrigger = styled.div`
  position: fixed;
  right: 0;
  top: 0;
  width: 20px;
  height: 100vh;
  z-index: 998;
`;

const Sidebar = styled.div`
  position: fixed;
  right: 0;
  top: 0;
  width: 300px;
  background-color: ${props => props.theme.surface};
  height: 100vh;
  box-shadow: -2px 0 5px ${props => props.theme.shadow};
  transform: ${props => props.show ? "translateX(0)" : "translateX(100%)"};
  transition: transform 0.3s ease-in-out;
  z-index: 999;
  padding: 20px;
  overflow-y: auto;
  color: ${props => props.theme.text};
`;

const SidebarHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
`;

const HistoryList = styled.div`
  display: flex;
  flex-direction: column;
  gap: 20px;
`;

const HistoryItem = styled.div`
  padding: 15px;
  border: 1px solid ${props => props.theme.border};
  border-radius: 8px;
  background-color: ${props => props.theme.surface};
  box-shadow: 0 1px 3px ${props => props.theme.shadow};
`;

const HistoryItemHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
`;

const HistoryImages = styled.div`
  display: flex;
  gap: 10px;
  margin-bottom: 10px;
`;

const HistoryImage = styled.img`
  width: 50%;
  height: auto;
  border-radius: 4px;
`;

const HistoryFooter = styled.div`
  font-size: 0.9em;
  color: ${props => props.theme.textSecondary};
  display: flex;
  justify-content: space-between;
`;

/**
 * 메모이제이션된 컴포넌트들
 * 불필요한 리렌더링을 방지하기 위해 React.memo 사용
 */
const MemoizedImageMagnifier = React.memo(ImageMagnifier);
const MemoizedLoadingSpinner = React.memo(LoadingSpinner);

/**
 * 히스토리 아이템 컴포넌트
 * 개별 히스토리 항목을 표시하는 메모이제이션된 컴포넌트
 */
const HistoryItemComponent = React.memo(({ item, onRestore, onDelete }) => (
  <HistoryItem
    role="listitem"
    aria-label={`History item: ${item.prompt}`}
  >
    <HistoryItemHeader>
      <div style={{ fontWeight: "bold" }}>
        {item.prompt}
      </div>
      <div style={{ display: "flex", gap: "8px" }}>
        <Button
          variant="success"
          onClick={() => onRestore(item)}
          aria-label={`Restore generation: ${item.prompt}`}
        >
          Restore
        </Button>
        <Button
          variant="danger"
          onClick={() => onDelete(item.id)}
          aria-label={`Delete history item: ${item.prompt}`}
        >
          Delete
        </Button>
      </div>
    </HistoryItemHeader>
    <HistoryImages>
      <HistoryImage src={item.initialImage} alt="Initial" />
      <HistoryImage src={item.finalImage} alt="Final" />
    </HistoryImages>
    <HistoryFooter>
      <span>{item.model}</span>
      <span>{item.timestamp}</span>
    </HistoryFooter>
  </HistoryItem>
));

/**
 * 모델 선택 컴포넌트
 * 스타일 변환에 사용할 모델을 선택하는 메모이제이션된 컴포넌트
 */
const ModelOption = styled.label`
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  padding: 8px;
  border-radius: 6px;
  transition: background-color 0.2s ease;

  &:hover {
    background-color: ${props => props.theme.background};
  }
`;

const ModelTooltip = styled.div`
  visibility: hidden;
  opacity: 0;
  position: absolute;
  left: 100%;
  top: 50%;
  transform: translateY(-50%);
  background-color: ${props => props.theme.surface};
  color: ${props => props.theme.text};
  padding: 12px;
  border-radius: 8px;
  font-size: 0.9rem;
  width: 250px;
  box-shadow: 0 2px 8px ${props => props.theme.shadow};
  z-index: 1000;
  transition: all 0.2s ease;
  margin-left: 10px;

  &::before {
    content: '';
    position: absolute;
    left: -6px;
    top: 50%;
    transform: translateY(-50%);
    border-width: 6px;
    border-style: solid;
    border-color: transparent ${props => props.theme.surface} transparent transparent;
  }
`;

const ModelOptionContainer = styled.div`
  position: relative;
  display: flex;
  align-items: center;

  &:hover ${ModelTooltip} {
    visibility: visible;
    opacity: 1;
  }
`;

const ProsConsList = styled.div`
  margin-top: 8px;
`;

const ProsConsItem = styled.div`
  display: flex;
  align-items: flex-start;
  gap: 4px;
  margin-bottom: 4px;
  font-size: 0.85rem;
`;

const ProsConsLabel = styled.span`
  font-weight: bold;
  min-width: 40px;
  color: ${props => props.isPro ? props.theme.success : props.theme.danger};
`;

const ModelSelectComponent = React.memo(({ selectedModel, onModelChange }) => (
  <ModelSelect>
    <ModelOptions>
      <ModelSection>
        <SectionTitle>Select Initial Model</SectionTitle>
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
          gap: "16px"
        }}>
          {INITIAL_MODEL_OPTIONS.map((option) => (
            <ModelCard
              key={option.id}
              isSelected={selectedModel === option.id}
              onClick={() => onModelChange(option.id)}
            >
              <ModelHeader>
                <ModelIcon option={option} />
                <ModelTitle>{option.label}</ModelTitle>
              </ModelHeader>
              <ModelDescription>
                {MODEL_DESCRIPTIONS[option.id].description}
              </ModelDescription>
              <ModelFeatures>
                <FeatureItem isPro>
                  <FeatureIcon>✓</FeatureIcon>
                  {MODEL_DESCRIPTIONS[option.id].pros[0]}
                </FeatureItem>
                <FeatureItem isPro={false}>
                  <FeatureIcon>✗</FeatureIcon>
                  {MODEL_DESCRIPTIONS[option.id].cons[0]}
                </FeatureItem>
              </ModelFeatures>
            </ModelCard>
          ))}
        </div>
      </ModelSection>
    </ModelOptions>
  </ModelSelect>
));

const ThemeToggle = styled.button`
  position: fixed;
  left: 20px;
  top: 20px;
  padding: 10px;
  border-radius: 50%;
  background-color: ${props => props.theme.surface};
  border: 1px solid ${props => props.theme.border};
  color: ${props => props.theme.text};
  cursor: pointer;
  z-index: 1000;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 4px ${props => props.theme.shadow};
  transition: all 0.3s ease;

  &:hover {
    transform: scale(1.1);
    background-color: ${props => props.theme.background};
  }
`;

const SliderPanel = styled.div`
  margin-top: 15px;
  padding: 15px;
  background-color: ${props => props.theme.surface};
  border: 1px solid ${props => props.theme.border};
  border-radius: 8px;
  display: ${props => props.show ? 'block' : 'none'};
`;

const SliderContainer = styled.div`
  margin-bottom: 15px;
  
  &:last-child {
    margin-bottom: 0;
  }
`;

const SliderHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
`;

const SliderLabel = styled.label`
  font-size: 0.9rem;
  color: ${props => props.theme.textSecondary};
`;

const SliderValue = styled.span`
  font-size: 0.9rem;
  color: ${props => props.theme.primary};
  font-weight: bold;
`;

const StyledSlider = styled.input.attrs({ type: 'range' })`
  width: 100%;
  height: 4px;
  border-radius: 2px;
  background: ${props => props.theme.border};
  outline: none;
  opacity: 0.7;
  transition: opacity 0.2s;
  -webkit-appearance: none;

  &:hover {
    opacity: 1;
  }

  &::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 16px;
    height: 16px;
    border-radius: 50%;
    background: ${props => props.theme.primary};
    cursor: pointer;
    transition: all 0.2s;

    &:hover {
      transform: scale(1.2);
    }
  }

  &::-moz-range-thumb {
    width: 16px;
    height: 16px;
    border-radius: 50%;
    background: ${props => props.theme.primary};
    cursor: pointer;
    transition: all 0.2s;

    &:hover {
      transform: scale(1.2);
    }
  }
`;

const PresetContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 16px;
`;

const PresetButton = styled.button`
  padding: 6px 12px;
  border-radius: 4px;
  border: 1px solid ${props => props.theme.border};
  background-color: ${props => props.active ? props.theme.primary : props.theme.surface};
  color: ${props => props.active ? 'white' : props.theme.text};
  cursor: pointer;
  transition: all 0.2s ease;
  font-size: 14px;
  font-weight: ${props => props.active ? 'bold' : 'normal'};

  &:hover {
    background-color: ${props => props.theme.primary};
    color: white;
    transform: translateY(-1px);
    box-shadow: 0 2px 4px ${props => props.theme.shadow};
  }

  &:active {
    transform: translateY(0);
  }
`;

const SavePresetButton = styled(PresetButton)`
  background-color: ${props => props.theme.success};
  color: white;
  border-color: ${props => props.theme.success};
  font-weight: bold;

  &:hover {
    background-color: ${props => props.theme.success};
    filter: brightness(1.1);
  }
`;

// 프리셋 정의
const STYLE_GAN_PRESETS = {
  Natural: {
    truncation: 0.7,
    noise: 0.3,
    strength: 0.6,
  },
  Artistic: {
    truncation: 0.9,
    noise: 0.7,
    strength: 0.8,
  },
  Bold: {
    truncation: 1.0,
    noise: 0.8,
    strength: 1.0,
  },
  Subtle: {
    truncation: 0.5,
    noise: 0.2,
    strength: 0.4,
  }
};

const TooltipContainer = styled.div`
  position: relative;
  display: inline-block;
  margin-left: 8px;
  cursor: help;

  &:hover > div {
    visibility: visible;
    opacity: 1;
  }
`;

const TooltipIcon = styled.div`
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background-color: ${props => props.theme.textSecondary};
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: bold;
`;

const TooltipText = styled.div`
  visibility: hidden;
  opacity: 0;
  position: absolute;
  left: 24px;
  top: 50%;
  transform: translateY(-50%);
  background-color: ${props => props.theme.tooltipBackground || props.theme.backgroundSecondary};
  color: ${props => props.theme.textColor};
  padding: 8px 12px;
  border-radius: 4px;
  font-size: 14px;
  width: 250px;
  transition: all 0.2s ease;
  z-index: 1000;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);

  &::before {
    content: '';
    position: absolute;
    left: -6px;
    top: 50%;
    transform: translateY(-50%);
    border-width: 6px;
    border-style: solid;
    border-color: transparent ${props => props.theme.tooltipBackground || props.theme.backgroundSecondary} transparent transparent;
  }
`;

const Tooltip = ({ text }) => (
  <TooltipContainer>
    <TooltipIcon>?</TooltipIcon>
    <TooltipText>{text}</TooltipText>
  </TooltipContainer>
);

// 파라미터 설명
const PARAMETER_DESCRIPTIONS = {
  truncation: "스타일의 다양성을 조절합니다. 높은 값(1.0)은 더 독특하고 창의적인 결과를, 낮은 값(0.1)은 더 안정적이고 일관된 결과를 생성합니다.",
  noise: "이미지의 세부 디테일 수준을 조절합니다. 높은 값은 더 많은 텍스처와 디테일을, 낮은 값은 더 부드럽고 깔끔한 결과를 만듭니다.",
  strength: "변환의 강도를 조절합니다. 높은 값은 원본 이미지를 크게 변형하고, 낮은 값은 미묘한 변화만을 적용합니다."
};

const PromptInputContainer = styled.div`
  position: relative;
  width: 100%;
`;

const PromptInputWrapper = styled.div`
  position: relative;
  width: 100%;
  margin-bottom: 8px;
`;

const PromptInput = styled(Input)`
  padding: 16px;
  font-size: 1.1rem;
  border: 2px solid ${props => props.hasError ? props.theme.danger : props.theme.border};
  border-radius: 8px;
  transition: all 0.3s ease;
  background-color: ${props => props.theme.surface};
  box-shadow: 0 2px 4px ${props => props.theme.shadow};
  line-height: 1.5;
  width: 94%;

  &:focus {
    border-color: ${props => props.theme.primary};
    box-shadow: 0 0 0 3px ${props => props.theme.primary}20;
    outline: none;
  }

  &::placeholder {
    color: ${props => props.theme.textSecondary};
    opacity: 0.7;
  }
`;

const PromptLabel = styled.label`
  display: block;
  margin-bottom: 8px;
  font-weight: 600;
  color: ${props => props.theme.text};
  font-size: 1.1rem;
`;

const PromptHint = styled.div`
  font-size: 0.9rem;
  color: ${props => props.theme.textSecondary};
  margin-top: 4px;
  display: flex;
  align-items: center;
  gap: 4px;
`;

const PromptExamples = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 12px;
`;

const ExampleButton = styled.button`
  padding: 6px 12px;
  border-radius: 16px;
  border: 1px solid ${props => props.theme.border};
  background-color: ${props => props.theme.surface};
  color: ${props => props.theme.text};
  font-size: 0.9rem;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    background-color: ${props => props.theme.primary};
    color: white;
    border-color: ${props => props.theme.primary};
  }
`;

const PromptCounter = styled.div`
  position: absolute;
  right: 12px;
  bottom: 12px;
  font-size: 0.8rem;
  color: ${props => {
    if (props.count > props.maxLength) return props.theme.danger;
    if (props.count > props.maxLength * 0.8) return props.theme.warning || '#ffa500';
    return props.theme.textSecondary;
  }};
`;

const PromptError = styled.div`
  color: ${props => props.theme.danger};
  font-size: 0.9rem;
  margin-top: 4px;
  display: flex;
  align-items: center;
  gap: 4px;
`;

// 프롬프트 예시 목록
const PROMPT_EXAMPLES = [
  "yellow T-shirt with blue stripes",
  "red leather jacket with silver zippers",
  "black denim jeans with ripped knees",
  "white cotton dress with floral pattern",
  "navy blue suit with gold buttons"
];

// Add Skeleton UI components after other styled components
const SkeletonContainer = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 16px;
`;

const SkeletonImage = styled.div`
  width: 100%;
  height: 400px;
  background: linear-gradient(
    90deg,
    ${props => props.theme.background} 25%,
    ${props => props.theme.backgroundLight} 50%,
    ${props => props.theme.background} 75%
  );
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
  border-radius: 8px;
  overflow: hidden;

  @keyframes shimmer {
    0% {
      background-position: 200% 0;
    }
    100% {
      background-position: -200% 0;
    }
  }
`;

const SkeletonText = styled.div`
  height: 20px;
  width: 60%;
  background: linear-gradient(
    90deg,
    ${props => props.theme.background} 25%,
    ${props => props.theme.backgroundLight} 50%,
    ${props => props.theme.background} 75%
  );
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
  border-radius: 4px;
`;

const SkeletonButton = styled.div`
  height: 40px;
  width: 120px;
  background: linear-gradient(
    90deg,
    ${props => props.theme.background} 25%,
    ${props => props.theme.backgroundLight} 50%,
    ${props => props.theme.background} 75%
  );
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
  border-radius: 20px;
`;

/**
 * 메인 ImageGeneratepage 컴포넌트
 * 전체 애플리케이션의 상태와 로직을 관리
 */
const ImageGeneratepage = () => {
  // 상태 관리
  const [styleGanParams, setStyleGanParams] = useState({
    truncation: 0.7,    // 기본값 0.7, 범위: 0.1 ~ 1.0
    noise: 0.5,         // 기본값 0.5, 범위: 0.0 ~ 1.0
    strength: 0.8      // 기본값 0.8, 범위: 0.1 ~ 1.0
  });

  const [state, setState] = useState({
    prompt: "",              // 텍스트 프롬프트
    initialImage: "",        // 초기 생성된 이미지
    finalImage: "",          // 변환된 이미지
    loading: false,          // 로딩 상태
    error: "",              // 에러 메시지
    selectedInitialModel: "Stable Diffusion 1.5",  // 초기 이미지 생성용 모델
    selectedFinalModel: "Disco GAN"     // 최종 이미지 생성용 모델
  });

  // 히스토리 상태 - localStorage와 동기화
  const [history, setHistory] = useState(() => {
    const savedHistory = localStorage.getItem('imageGenerationHistory');
    return savedHistory ? JSON.parse(savedHistory) : [];
  });

  // 사이드바 표시 상태
  const [showSidebar, setShowSidebar] = useState(false);

  // Refs
  const imageSectionRef = useRef(null);
  const sidebarTimeoutRef = useRef(null);

  // 메모이제이션된 값들
  const isGenerateDisabled = useMemo(() =>
    state.loading || !state.prompt,
    [state.loading, state.prompt]
  );

  const canShowModelSelect = useMemo(() =>
    Boolean(state.initialImage),
    [state.initialImage]
  );

  // 다크모드 상태 관리
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const savedTheme = localStorage.getItem('theme');
    return savedTheme ? savedTheme === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches;
  });

  // 다크모드 변경 시 localStorage 저장
  useEffect(() => {
    localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
  }, [isDarkMode]);

  // 효과
  useEffect(() => {
    // 히스토리 변경 시 localStorage에 저장
    localStorage.setItem('imageGenerationHistory', JSON.stringify(history));
  }, [history]);

  // 커스텀 프리셋 상태 관리
  const [customPresets, setCustomPresets] = useState(() => {
    const saved = localStorage.getItem('styleGanCustomPresets');
    return saved ? JSON.parse(saved) : {};
  });

  // 현재 선택된 프리셋 상태
  const [activePreset, setActivePreset] = useState(null);

  // 프리셋 적용 함수
  const handlePresetClick = useCallback((presetName, presetValues) => {
    setStyleGanParams(presetValues);
    setActivePreset(presetName);
  }, []);

  // 현재 설정을 새 프리셋으로 저장
  const handleSavePreset = useCallback(() => {
    const presetName = prompt('Enter a name for this preset:');
    if (presetName) {
      const newPresets = {
        ...customPresets,
        [presetName]: { ...styleGanParams }
      };
      setCustomPresets(newPresets);
      localStorage.setItem('styleGanCustomPresets', JSON.stringify(newPresets));
      setActivePreset(presetName);
    }
  }, [customPresets, styleGanParams]);

  // 파라미터 변경 시 activePreset 초기화
  const handleStyleGanParamChange = useCallback((param, value) => {
    setStyleGanParams(prev => ({
      ...prev,
      [param]: value
    }));
    setActivePreset(null);  // 파라미터가 변경되면 현재 선택된 프리셋 초기화
  }, []);

  // 콜백 함수들
  /**
   * 히스토리 항목 삭제 처리
   */
  const handleDeleteHistory = useCallback((id) => {
    setHistory(prev => prev.filter(item => item.id !== id));
  }, []);

  /**
   * 히스토리 전체 삭제 처리
   */
  const handleClearHistory = useCallback(() => {
    if (window.confirm('모든 히스토리를 삭제하시겠습니까?')) {
      setHistory([]);
    }
  }, []);

  /**
   * 히스토리 항목 복원 처리
   */
  const handleRestoreHistory = useCallback((item) => {
    setState(prev => ({
      ...prev,
      prompt: item.prompt,
      initialImage: item.initialImage,
      finalImage: item.finalImage,
      selectedInitialModel: item.model,
      selectedFinalModel: item.model
    }));

    // Style GAN-ada 파라미터 복원
    if (item.parameters) {
      setStyleGanParams(item.parameters);
    }
  }, []);

  /**
   * 히스토리 내보내기 처리
   */
  const handleExportHistory = useCallback(() => {
    const historyData = JSON.stringify(history, null, 2);
    const blob = new Blob([historyData], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fashion-fusion-history-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }, [history]);

  /**
   * 히스토리 가져오기 처리
   */
  const handleImportHistory = useCallback((event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const importedHistory = JSON.parse(e.target.result);
          if (Array.isArray(importedHistory)) {
            if (window.confirm('기존 히스토리에 추가하시겠습니까? "취소"를 선택하면 기존 히스토리를 대체합니다.')) {
              setHistory(prev => [...prev, ...importedHistory]);
            } else {
              setHistory(importedHistory);
            }
          }
        } catch (err) {
          alert('잘못된 형식의 파일입니다.');
        }
      };
      reader.readAsText(file);
    }
    event.target.value = '';
  }, []);

  /**
   * 초기 이미지 생성 처리
   */
  const handleInitialGeneration = useCallback(async (seed) => {
    if (!state.prompt || !state.selectedInitialModel) return;

    setState(prev => ({ ...prev, loading: true, error: "" }));

    try {
      if (USE_DUMMY_DATA) {
        await new Promise(resolve => setTimeout(resolve, 1000));
        setState(prev => ({
          ...prev,
          initialImage: DUMMY_IMAGES[state.selectedInitialModel].INITIAL,
          finalImage: ""
        }));
      } else {
        const imageData = await generateInitialImage(state.prompt, state.selectedInitialModel, seed);
        // base64 데이터를 data URL 형식으로 변환
        const imageUrl = `data:image/png;base64,${imageData}`;
        setState(prev => ({
          ...prev,
          initialImage: imageUrl,
          finalImage: ""
        }));
      }
    } catch (err) {
      setState(prev => ({ ...prev, error: err.message }));
    } finally {
      setState(prev => ({ ...prev, loading: false }));
    }
  }, [state.prompt, state.selectedInitialModel]);

  /**
   * 최종 이미지 변환 처리
   */
  const handleFinalGeneration = useCallback(async (seed) => {
    if (!state.initialImage) return;

    setState(prev => ({ ...prev, loading: true, error: "" }));

    try {
      if (USE_DUMMY_DATA) {
        await new Promise(resolve => setTimeout(resolve, 1000));
        setState(prev => ({
          ...prev,
          finalImage: DUMMY_IMAGES[state.selectedFinalModel].FINAL
        }));
      } else {
        const imageData = await generateFinalImage(state.initialImage, state.selectedFinalModel, seed);
        setState(prev => ({
          ...prev,
          finalImage: `data:image/png;base64,${imageData}`
        }));
      }
    } catch (err) {
      setState(prev => ({ ...prev, error: err.message }));
    } finally {
      setState(prev => ({ ...prev, loading: false }));
    }
  }, [state.initialImage, state.selectedFinalModel]);

  /**
   * 이미지 재생성 처리
   */
  const handleRegenerate = useCallback(() => {
    if (state.finalImage) {
      // 랜덤 시드 생성 (0-1000000 사이의 정수)
      const seed = Math.floor(Math.random() * 1000000);
      handleFinalGeneration(seed);
    } else {
      // 랜덤 시드 생성 (0-1000000 사이의 정수)
      const seed = Math.floor(Math.random() * 1000000);
      handleInitialGeneration(seed);
    }
  }, [state.finalImage, handleFinalGeneration, handleInitialGeneration]);

  /**
   * 모든 입력 초기화 처리
   */
  const handleReset = useCallback(() => {
    setState(prev => ({
      ...prev,
      prompt: "",
      initialImage: "",
      finalImage: "",
      error: ""
    }));
    setStyleGanParams({
      truncation: 0.7,
      noise: 0.5,
      strength: 0.8
    });
  }, []);

  /**
   * 모델 변경 처리
   */
  const handleInitialModelChange = useCallback((model) => {
    setState(prev => ({ ...prev, selectedInitialModel: model }));
  }, []);

  const handleFinalModelChange = useCallback((model) => {
    setState(prev => ({ ...prev, selectedFinalModel: model }));
  }, []);

  // 렌더링 메서드들
  /**
   * 프롬프트 표시 영역 렌더링
   */
  const renderPromptDisplay = useMemo(() => (
    state.prompt && (
      <PromptDisplay>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <span style={{ fontWeight: "bold" }}>prompt:</span>
          <span>{state.prompt}</span>
        </div>
      </PromptDisplay>
    )
  ), [state.prompt]);

  /**
   * 히스토리 항목들 렌더링
   */
  const renderHistoryItems = useMemo(() => (
    history.map(item => (
      <HistoryItemComponent
        key={item.id}
        item={item}
        onRestore={handleRestoreHistory}
        onDelete={handleDeleteHistory}
      />
    ))
  ), [history, handleRestoreHistory, handleDeleteHistory]);

  return (
    <ThemeProvider theme={isDarkMode ? darkTheme : lightTheme}>
      <GlobalStyle />
      <Container>
        <ThemeToggle
          onClick={() => setIsDarkMode(!isDarkMode)}
          aria-label={isDarkMode ? "Switch to light mode" : "Switch to dark mode"}
        >
          {isDarkMode ? '🌞' : '🌙'}
        </ThemeToggle>
        <MainContent>
          {renderPromptDisplay}
          <ContentArea>
            <ImageControlArea>
              {/* Initial Model Selection and Prompt Input - Only visible when no images exist */}
              {!state.initialImage && !state.finalImage && (
                <>
                  <ModelSelect>
                    <ModelOptions>
                      <ModelSection>
                        <SectionTitle>Select Initial Model</SectionTitle>
                        <div style={{
                          display: "grid",
                          gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
                          gap: "16px"
                        }}>
                          {INITIAL_MODEL_OPTIONS.map((option) => (
                            <ModelCard
                              key={option.id}
                              isSelected={state.selectedInitialModel === option.id}
                              onClick={() => handleInitialModelChange(option.id)}
                            >
                              <ModelHeader>
                                <ModelIcon option={option} />
                                <ModelTitle>{option.label}</ModelTitle>
                              </ModelHeader>
                              <ModelDescription>
                                {MODEL_DESCRIPTIONS[option.id].description}
                              </ModelDescription>
                              <ModelFeatures>
                                <FeatureItem isPro>
                                  <FeatureIcon>✓</FeatureIcon>
                                  {MODEL_DESCRIPTIONS[option.id].pros[0]}
                                </FeatureItem>
                                <FeatureItem isPro={false}>
                                  <FeatureIcon>✗</FeatureIcon>
                                  {MODEL_DESCRIPTIONS[option.id].cons[0]}
                                </FeatureItem>
                              </ModelFeatures>
                            </ModelCard>
                          ))}
                        </div>
                      </ModelSection>
                    </ModelOptions>
                  </ModelSelect>

                  <Form
                    onSubmit={(e) => {
                      e.preventDefault();
                      // 랜덤 시드 생성 (0-1000000 사이의 정수)
                      const seed = Math.floor(Math.random() * 1000000);
                      handleInitialGeneration(seed);
                    }}
                    aria-label="Image generation form"
                  >
                    <PromptInputContainer>
                      <PromptLabel htmlFor="prompt-input">Describe your fashion item</PromptLabel>
                      <PromptInputWrapper>
                        <PromptInput
                          id="prompt-input"
                          type="text"
                          value={state.prompt}
                          onChange={(e) => setState(prev => ({ ...prev, prompt: e.target.value }))}
                          placeholder="Enter a detailed description of the fashion item you want to generate..."
                          disabled={state.loading}
                          aria-required="true"
                          maxLength={200}
                          hasError={state.error}
                        />
                        <PromptCounter count={state.prompt.length} maxLength={200}>
                          {state.prompt.length}/200
                        </PromptCounter>
                      </PromptInputWrapper>
                      <PromptHint>
                        💡 Tip: Be specific about colors, materials, and style details
                      </PromptHint>
                      {state.error && (
                        <PromptError>
                          ⚠️ {state.error}
                        </PromptError>
                      )}
                      <PromptExamples>
                        {PROMPT_EXAMPLES.map((example, index) => (
                          <ExampleButton
                            key={index}
                            onClick={() => setState(prev => ({ ...prev, prompt: example }))}
                            type="button"
                          >
                            {example}
                          </ExampleButton>
                        ))}
                      </PromptExamples>
                    </PromptInputContainer>
                    <Button
                      type="submit"
                      disabled={isGenerateDisabled || !state.selectedInitialModel}
                      aria-label="Generate initial image"
                      style={{ marginTop: '16px' }}
                    >
                      Generate Image
                    </Button>
                  </Form>
                </>
              )}

              {/* Final Model Selection - Visible after initial image generation */}
              {state.initialImage && (
                <>
                  <ModelSelect>
                    <ModelOptions>
                      <ModelSection>
                        <SectionTitle>Select Final Model</SectionTitle>
                        <div style={{
                          display: "grid",
                          gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
                          gap: "16px"
                        }}>
                          {FINAL_MODEL_OPTIONS.map((option) => (
                            <ModelCard
                              key={option.id}
                              isSelected={state.selectedFinalModel === option.id}
                              onClick={() => handleFinalModelChange(option.id)}
                            >
                              <ModelHeader>
                                <ModelIcon option={option} />
                                <ModelTitle>{option.label}</ModelTitle>
                              </ModelHeader>
                              <ModelDescription>
                                {MODEL_DESCRIPTIONS[option.id].description}
                              </ModelDescription>
                              <ModelFeatures>
                                <FeatureItem isPro>
                                  <FeatureIcon>✓</FeatureIcon>
                                  {MODEL_DESCRIPTIONS[option.id].pros[0]}
                                </FeatureItem>
                                <FeatureItem isPro={false}>
                                  <FeatureIcon>✗</FeatureIcon>
                                  {MODEL_DESCRIPTIONS[option.id].cons[0]}
                                </FeatureItem>
                              </ModelFeatures>
                            </ModelCard>
                          ))}
                        </div>
                      </ModelSection>
                    </ModelOptions>
                  </ModelSelect>

                  {/* Style GAN-ada Parameters */}
                  <SliderPanel show={state.selectedFinalModel === "Style GAN-ada"}>
                    {/* Presets */}
                    <PresetContainer>
                      {Object.entries(STYLE_GAN_PRESETS).map(([name, values]) => (
                        <PresetButton
                          key={name}
                          active={activePreset === name}
                          onClick={() => handlePresetClick(name, values)}
                        >
                          {name}
                        </PresetButton>
                      ))}
                      {Object.entries(customPresets).map(([name, values]) => (
                        <PresetButton
                          key={name}
                          active={activePreset === name}
                          onClick={() => handlePresetClick(name, values)}
                        >
                          {name}
                        </PresetButton>
                      ))}
                      <SavePresetButton onClick={handleSavePreset}>
                        Save Current
                      </SavePresetButton>
                    </PresetContainer>

                    <SliderContainer>
                      <SliderHeader>
                        <div style={{ display: 'flex', alignItems: 'center' }}>
                          <SliderLabel>Truncation (Style Variation)</SliderLabel>
                          <Tooltip text={PARAMETER_DESCRIPTIONS.truncation} />
                        </div>
                        <SliderValue>{styleGanParams.truncation.toFixed(2)}</SliderValue>
                      </SliderHeader>
                      <StyledSlider
                        min="0.1"
                        max="1.0"
                        step="0.01"
                        value={styleGanParams.truncation}
                        onChange={(e) => handleStyleGanParamChange('truncation', parseFloat(e.target.value))}
                        aria-label="Style variation control"
                      />
                    </SliderContainer>

                    <SliderContainer>
                      <SliderHeader>
                        <div style={{ display: 'flex', alignItems: 'center' }}>
                          <SliderLabel>Noise (Detail Level)</SliderLabel>
                          <Tooltip text={PARAMETER_DESCRIPTIONS.noise} />
                        </div>
                        <SliderValue>{styleGanParams.noise.toFixed(2)}</SliderValue>
                      </SliderHeader>
                      <StyledSlider
                        min="0.0"
                        max="1.0"
                        step="0.01"
                        value={styleGanParams.noise}
                        onChange={(e) => handleStyleGanParamChange('noise', parseFloat(e.target.value))}
                        aria-label="Noise level control"
                      />
                    </SliderContainer>

                    <SliderContainer>
                      <SliderHeader>
                        <div style={{ display: 'flex', alignItems: 'center' }}>
                          <SliderLabel>Strength (Transform Intensity)</SliderLabel>
                          <Tooltip text={PARAMETER_DESCRIPTIONS.strength} />
                        </div>
                        <SliderValue>{styleGanParams.strength.toFixed(2)}</SliderValue>
                      </SliderHeader>
                      <StyledSlider
                        min="0.1"
                        max="1.0"
                        step="0.01"
                        value={styleGanParams.strength}
                        onChange={(e) => handleStyleGanParamChange('strength', parseFloat(e.target.value))}
                        aria-label="Transform strength control"
                      />
                    </SliderContainer>
                  </SliderPanel>
                </>
              )}

              {/* Image display logic */}
              {state.initialImage && !state.finalImage && (
                <ImageContainer>
                  {state.loading && (
                    <LoadingOverlay>
                      <SkeletonContainer>
                        <SkeletonImage />
                        <SkeletonText />
                        <SkeletonText />
                        <SkeletonButton />
                      </SkeletonContainer>
                    </LoadingOverlay>
                  )}
                  <MemoizedImageMagnifier
                    imageUrl={state.initialImage}
                    alt="Initial"
                  />
                </ImageContainer>
              )}

              {state.loading && !state.initialImage && (
                <ImageContainer>
                  <SkeletonContainer>
                    <SkeletonImage />
                    <SkeletonText />
                    <SkeletonText />
                    <SkeletonButton />
                  </SkeletonContainer>
                </ImageContainer>
              )}

              {state.finalImage && (
                <ImageContainer>
                  {state.loading && (
                    <LoadingOverlay>
                      <SkeletonContainer>
                        <SkeletonImage />
                        <SkeletonText />
                        <SkeletonText />
                        <SkeletonButton />
                      </SkeletonContainer>
                    </LoadingOverlay>
                  )}
                  <MemoizedImageMagnifier
                    imageUrl={state.finalImage}
                    alt="Transformed"
                  />
                </ImageContainer>
              )}

              {/* Button controls */}
              {state.initialImage && (
                <ButtonGroup role="group" aria-label="Image control buttons">
                  <Button
                    onClick={handleRegenerate}
                    disabled={state.loading}
                    aria-label="Regenerate image"
                  >
                    regenerate
                  </Button>
                  <Button
                    onClick={handleReset}
                    disabled={state.loading}
                    aria-label="Reset all inputs"
                  >
                    reset
                  </Button>
                  {!state.finalImage ? (
                    <Button
                      onClick={() => {
                        // 랜덤 시드 생성 (0-1000000 사이의 정수)
                        const seed = Math.floor(Math.random() * 1000000);
                        handleFinalGeneration(seed);
                      }}
                      disabled={state.loading || !state.selectedFinalModel}
                      aria-label="Transform image style"
                    >
                      style transform
                    </Button>
                  ) : (
                    <Button
                      variant="success"
                      onClick={() => {
                        const byteCharacters = atob(state.finalImage.split(',')[1]);
                        const byteNumbers = new Array(byteCharacters.length);
                        for (let i = 0; i < byteCharacters.length; i++) {
                          byteNumbers[i] = byteCharacters.charCodeAt(i);
                        }
                        const byteArray = new Uint8Array(byteNumbers);
                        const blob = new Blob([byteArray], { type: 'image/png' });
                        const url = window.URL.createObjectURL(blob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = 'transformed_image.png';
                        document.body.appendChild(a);
                        a.click();
                        window.URL.revokeObjectURL(url);
                        document.body.removeChild(a);
                      }}
                      aria-label="Download transformed image"
                    >
                      download
                    </Button>
                  )}
                </ButtonGroup>
              )}
            </ImageControlArea>
          </ContentArea>

          {state.error && (
            <ErrorMessage>
              <p>{state.error}</p>
            </ErrorMessage>
          )}
        </MainContent>

        <HistoryButton showSidebar={showSidebar}>
          <Button
            onClick={() => setShowSidebar(!showSidebar)}
            aria-expanded={showSidebar}
            aria-controls="history-sidebar"
            aria-label={showSidebar ? "Hide history sidebar" : "Show history sidebar"}
          >
            {showSidebar ? "Hide History" : "Show History"}
          </Button>
        </HistoryButton>

        <SidebarTrigger
          onMouseEnter={() => {
            if (sidebarTimeoutRef.current) {
              clearTimeout(sidebarTimeoutRef.current);
            }
            setShowSidebar(true);
          }}
        />

        <Sidebar
          show={showSidebar}
          onMouseLeave={() => {
            sidebarTimeoutRef.current = setTimeout(() => {
              setShowSidebar(false);
            }, 300);
          }}
          role="complementary"
          aria-label="Generation history"
          id="history-sidebar"
        >
          <SidebarHeader>
            <h3 style={{ margin: 0 }}>Generation History</h3>
            <div style={{ display: "flex", gap: "8px" }}>
              {history.length > 0 && (
                <>
                  <Button
                    variant="success"
                    onClick={handleExportHistory}
                    aria-label="Export history"
                  >
                    Export
                  </Button>
                  <Button
                    variant="danger"
                    onClick={handleClearHistory}
                    aria-label="Clear all history"
                  >
                    Clear All
                  </Button>
                </>
              )}
              <input
                type="file"
                accept=".json"
                onChange={handleImportHistory}
                style={{ display: "none" }}
                id="history-import"
                aria-label="Import history from file"
              />
              <Button
                onClick={() => document.getElementById('history-import').click()}
                aria-label="Import history"
              >
                Import
              </Button>
            </div>
          </SidebarHeader>

          <HistoryList role="list" aria-label="History items">
            {renderHistoryItems}
            {history.length === 0 && (
              <div style={{
                textAlign: "center",
                color: "#666",
                padding: "20px"
              }}>
                No history yet
              </div>
            )}
          </HistoryList>
        </Sidebar>
      </Container>
    </ThemeProvider>
  );
};

export default ImageGeneratepage;
