export const USE_DUMMY_DATA = true;

export const DUMMY_IMAGES = {
  "Stable Diffusion 1.5": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#FF6B6B"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 1.5</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#FF8787"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 1.5</text>
      </svg>
    `)}`
  },
  "Stable Diffusion 3.5": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4D96FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 3.5</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#6BA6FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Stable Diffusion 3.5</text>
      </svg>
    `)}`
  },
  "Disco GAN": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4D96FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Disco GAN</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#9C27B0"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Disco GAN</text>
      </svg>
    `)}`
  },
  "Style GAN-ada": {
    INITIAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4D96FF"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Generated by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Style GAN-ada</text>
      </svg>
    `)}`,
    FINAL: `data:image/svg+xml,${encodeURIComponent(`
      <svg width="400" height="400" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#4CAF50"/>
        <text x="50%" y="40%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Transformed by</text>
        <text x="50%" y="60%" font-family="Arial" font-size="24" fill="white" text-anchor="middle" dy=".3em">Style GAN-ada</text>
      </svg>
    `)}`
  }
}; 